"""add metrics table

Revision ID: 63933d4f952f
Revises: 1358cf6e1a5d
Create Date: 2026-05-30 18:59:15.626782
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Идентификаторы ревизий Alembic
revision: str = "63933d4f952f"
down_revision: str | Sequence[str] | None = "1358cf6e1a5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Применение миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metrics",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор записи"),
        sa.Column("service", sa.String(length=50), nullable=False, comment="Источник"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Название"),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Метки в формате JSON",
        ),
        sa.Column("value", sa.Float(), nullable=False, comment="Значение метрики"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metrics")),
        sa.UniqueConstraint("service", "name", "labels", name="uq_metric_identity"),
    )
    op.create_index(op.f("ix_metrics_name"), "metrics", ["name"], unique=False)
    op.create_index(op.f("ix_metrics_service"), "metrics", ["service"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metrics_service"), table_name="metrics")
    op.drop_index(op.f("ix_metrics_name"), table_name="metrics")
    op.drop_table("metrics")
    # ### end Alembic commands ###
