"""add fsm state table

Revision ID: 1358cf6e1a5d
Revises: 1966af731f5d
Create Date: 2026-05-22 14:14:34.451638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Идентификаторы ревизий Alembic
revision: str = "1358cf6e1a5d"
down_revision: str | Sequence[str] | None = "1966af731f5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Применение миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fsm_states",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор записи"),
        sa.Column("bot_id", sa.BigInteger(), nullable=False, comment="ID бота"),
        sa.Column("chat_id", sa.BigInteger(), nullable=False, comment="ID чата"),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="ID юзера"),
        sa.Column("destiny", sa.String(), nullable=False, comment="Маркер изоляции"),
        sa.Column("state", sa.String(), nullable=True, comment="Текущий стейт"),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Данные FSM"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fsm_states")),
        sa.UniqueConstraint("bot_id", "chat_id", "user_id", "destiny", name="uq_fsm_composite_key"),
    )
    op.create_index(op.f("ix_fsm_states_bot_id"), "fsm_states", ["bot_id"], unique=False)
    op.create_index(op.f("ix_fsm_states_chat_id"), "fsm_states", ["chat_id"], unique=False)
    op.create_index(op.f("ix_fsm_states_user_id"), "fsm_states", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fsm_states_user_id"), table_name="fsm_states")
    op.drop_index(op.f("ix_fsm_states_chat_id"), table_name="fsm_states")
    op.drop_index(op.f("ix_fsm_states_bot_id"), table_name="fsm_states")
    op.drop_table("fsm_states")
    # ### end Alembic commands ###
