"""add lang field to users

Revision ID: 1966af731f5d
Revises:
Create Date: 2026-05-19 15:10:10.164788
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Идентификаторы ревизий Alembic
revision: str = "1966af731f5d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Применение миграции."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор записи"),
        sa.Column("tg_id", sa.BigInteger(), nullable=False, comment="Telegram ID"),
        sa.Column("first_name", sa.String(length=255), nullable=False, comment="Имя"),
        sa.Column("last_name", sa.String(length=255), nullable=True, comment="Фамилия"),
        sa.Column("username", sa.String(length=255), nullable=True, comment="Username"),
        sa.Column("lang", sa.String(length=10), nullable=True, comment="Код языка"),
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Администратор",
        ),
        sa.Column(
            "is_banned",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Заблокирован",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_is_admin"), "users", ["is_admin"], unique=False)
    op.create_index(op.f("ix_users_is_banned"), "users", ["is_banned"], unique=False)
    op.create_index(op.f("ix_users_tg_id"), "users", ["tg_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат миграции."""

    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_tg_id"), table_name="users")
    op.drop_index(op.f("ix_users_is_banned"), table_name="users")
    op.drop_index(op.f("ix_users_is_admin"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
